# 7 异常处理

# 7.1 抛出异常

通过throw抛出，可以定义一般类异常

```cpp
class iterator_overflow {
public:
    iterator_overflow(int index, int max): _index(index), _max(max){}
    int index() {return _index;}
    int max() {return _max;}
    
    void what_happend( ostream &os = cerr) {
        os << "Internal error: current index"
        << _index <<"exceeds maximum bound: "
        << _max;
    }
private:
    int _index;
    int _max;
};

//用法如下
if (...)
	itrator_overflow ex(_index, Triangular::_max_elems);
	throw ex;
```

# 7.2-3 捕获异常 - 异常提炼

我们可以利用单条或者一连串的cathc来捕获被抛出的异常。

catch前需要搭配try的格式来实现

```cpp
try {
        PrintIt<ostream> to_standard_out(cout);
        to_standard_out.print("Hello world");
    }
    catch (int num) {
        cout << num << "错误出现了" << endl;
    }
```

可以在catch块内处理后继续将异常通过throw抛出

## 异常处理的方式与传递

异常处理机制是查看异常由何处抛出，判断是否位于try块内，如果是，则检验相应的catch块字句看是否能具备处理此异常的能力，如果可以，异常便被处理，而程序也就继续执行下去。

如果判断不在try块内，则会暂停执行，并不断上溯到调用者看看是否处于try块内，如果是则catch块来处理；如果一直上溯到顶层main函数依然没有办法处理，则调用标准库terminate()，中断整个app的运行

> 当函数的try块发生某个异常，但并没有相应的catch子句来捕获它，此函数便会中断，由异常处理机制接管，沿着“**函数调用链**”一路回溯，搜寻符合条件的catch子句。
> 

# 7.4 局部资源管理

在异常处理机制终结某个函数之前，C++保证函数中所有的局部对象的destructor都会被调用（释放资源）

auto_ptr是标准库提供的一个class template，它会自动删除通过new表达式分配的对象。使用必须先包含memory头文件

```cpp
#include <memory>
auto_ptr< string > aps(new string( "vermeer" ));
```

# 7.5 标准异常